### ISSUE TITLE
Problem in Article: EF Core 2.0 Many-to-many relationships Part 4: A more general abstraction

### ISSUE THREAD

**Issue by lenraven** [ajcvickers/ajcvickers.github.io#10]
Hi Arthur!

I found a problem in your article:
**EF Core 2.0 Many-to-many relationships Part 4: A more general abstraction**

The problem is in the implementation of JoinCollectionFacade.

When you call a ToList on an instance of JoinCollectionFacade and there are items in the collection, it will case StackOverflowException.

The reason is that the ToList implementation will call the CopyTo method of facade.
And the CopyTo method is calling the ToList.

Best Regards,
Norbert

**Comment by ajcvickers** [comment]
@lenraven Interesting. Feel free to submit a PR if you know how to fix it.
